title: "Blog Post"
author: ruhidesai
email: rdesai3@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Here's a little bit about myself:)

# social links
twitter_username: ruhi_desai # DO NOT include the @ character, or else the build will fail!
github_username:  ruhidesai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
